### PR TITLE
workflow for modules

### PR DESCRIPTION
**Pull request by krankenbro**
Added workflow for modules

### CODE REVIEW

**Comment by mvktsk** [comment]
Review task https://virtocommerce.atlassian.net/browse/VP-3967 has been created

**Comment by t13ka** [comment]
This commit messages are not consistent with our style guide:
image

@krankenbro would you mind to read this https://github.com/VirtoCommerce/styleguide/blob/master/gitcommits.md ? :)

**Comment by krankenbro** [comment]
@t13ka oops, it was meant to be squashed...

**Comment by t13ka** [comment]
@krankenbro perhaps, the best way be independent of that it is to follow always our agreements :) then all your commits messages will look good

**Pull request merged**
